// let fonts = {
//   'home': 'e96a',
//   'globe': 'e901'
// }
let icons = {
"icon-accept":"\e900",
"icon-address_settings":"\e901",
"icon-attachment":"\e902",
"icon-Avatar_male":"\e903",
"icon-back_screen_black":"\e904",
"icon-back_screen_white":"\e905",
"icon-call_support":"\e906",
"icon-change_password_settings":"\e907",
"icon-check_interest":"\e908",
"icon-choices":"\e909",
"icon-Contacts_flow":"\e90a",
"icon-contacts_profile":"\e90b",
"icon-contacts":"\e90c",
"icon-coworker":"\e90d",
"icon-Credit_card_add":"\e90e",
"icon-cross":"\e90f",
"icon-designation_profile":"\e910",
"icon-discover":"\e911",
"icon-done":"\e912",
"icon-Dropdown_arrow":"\e913",
"icon-edit-profile":"\e914",
"icon-emoticons":"\e915",
"icon-expires_in_filled":"\e916",
"icon-expires_in":"\e917",
"icon-family":"\e918",
"icon-free_trial_filled":"\e919",
"icon-free_trial":"\e91a",
"icon-friend-request":"\e91b",
"icon-help_profile":"\e91c",
"icon-help":"\e91d",
"icon-inbox":"\e91e",
"icon-input":"\e91f",
"icon-interest_selected":"\e920",
"icon-interest":"\e921",
"icon-interests_profile":"\e922",
"icon-left_arow":"\e923",
"icon-location_profile_filled":"\e924",
"icon-location_profile":"\e925",
"icon-microphone":"\e926",
"icon-minus":"\e927",
"icon-my_services":"\e928",
"icon-notification_settings":"\e929",
"icon-notifications":"\e92a",
"icon-offer_expires_in":"\e92b",
"icon-offer_starts_in_filled":"\e92c",
"icon-offer_starts_in":"\e92d",
"icon-option_menu_3dots":"\e92e",
"icon-Payment_history":"\e92f",
"icon-payment_settings":"\e930",
"icon-plans":"\e931",
"icon-plus":"\e932",
"icon-Privacy_Policy_profile":"\e933",
"icon-profile_avatar_header":"\e934",
"icon-profile_settings":"\e935",
"icon-qrt":"\e936",
"icon-quantity_filled":"\e937",
"icon-quantity":"\e938",
"icon-reattempt_payment":"\e939",
"icon-reject":"\e93a",
"icon-Remove_credit_card":"\e93b",
"icon-requests_friends":"\e93c",
"icon-right_arrow":"\e93d",
"icon-save_filled":"\e93e",
"icon-save":"\e93f",
"icon-seen_message":"\e940",
"icon-select_members":"\e941",
"icon-send_message":"\e942",
"icon-settings_profile":"\e943",
"icon-settings":"\e944",
"icon-share-filled":"\e948",
"icon-Share":"\e949",
"icon-signout_profile":"\e94a",
"icon-Star_Empty":"\e94b",
"icon-Star_filled":"\e94c",
"icon-support":"\e94d",
"icon-terms_profile":"\e94e",
"icon-title_profile":"\e94f",
"icon-web_filled":"\e950",
"icon-web":"\e951",
};


export default icons;
