/**
 * Created by Shoaib on 1/18/2017.
 */
DummyDetailedCard =
  { cardId: 'a7edad42dda74b099cb38c2455a0db31',
    campaignId: 'CN201701183',
    cardTitle: 'Create the next best logo for your company  for your company',
    cardDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, ',
    likes: 0,
    shares: 0,
    cardTags: [],
    mediaType: 'image',
    primaryMediaUrl: 'https://res.cloudinary.com/servup/image/upload/v1484736729/kwcslw90rljiq6wxrxmc.jpg',
    additionalMediaUrls:
      [ 'https://res.cloudinary.com/servup/image/upload/v1484736729/wykrzidbkxvsdo3xpfu5.jpg',
        'https://res.cloudinary.com/servup/image/upload/v1484736729/r09owdthwvzu7smslawd.jpg' ],
    callToAction: 'book',
    listOfAttributes: [],
    cardQuestion: [],
    returnPolicy: 'DDSAD cFEDASD DADSDDSDS',
    termsOfServices: 'SAXZXDSAdsa',
    warrantyUrl: null,
    overallRating: 0,
    spName: 'the beaming soul',
    spLogo: '',
    topReview: null,
    numberOfReviews: 0,
    plans:
      [ { planType: 'free',
        planName: '',
        planDescription: '',
        price: { amount: 0, currency: '', currencySymbol: '' },
        isShippingChargesRequired: false,
        shippingCharges: { amount: 0, currency: '', currencySymbol: '' },
        startsOn: '',
        endsOn: '',
        displayPrice: { amount: 0, currency: '', currencySymbol: '' },
        displayPriceUnit: '',
        displayPriceNotes: '',
        invoicingCylcle: '',
        subsciptionSchedule:
          { startDateTime: '0001-01-01T00:00:00Z',
            endDateTime: '0001-01-01T00:00:00Z' },
        subsciptionPeriod: { unitOfPeriod: '', countOfPeriod: 0 },
        appliesTo: '',
        noOfAllowedUsers: 0,
        minSubPeriod: { unitOfPeriod: '', countOfPeriod: 0 },
        freeTrialPeriod: { unitOfPeriod: '', countOfPeriod: 0 },
        signupFee: { amount: 0, currency: '', currencySymbol: '' },
        id: '4fd3c41147ce416086cea9bf0b6adc30' } ],
    segments: [],
    groups: [],
    interests: [],
    spPublicId: 'f84e6769d1b340839091d74934a94ea5' };
export default DummyDetailedCard;
